
package com.mycompany.phase1;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author almazyadn
 */
public class test extends JFrame {

    private JTextField nameField;
    private JButton pairButton;
    private JButton leaveButton;

    public test() {
        // إعداد الفريم
        setTitle("Start Room");
        setSize(400, 300);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLayout(null);

        // حقل إدخال الاسم
        JLabel nameLabel = new JLabel("Enter your name:");
        nameLabel.setBounds(50, 50, 150, 20);
        add(nameLabel);

        nameField = new JTextField();
        nameField.setBounds(50, 80, 200, 25);
        add(nameField);

        // زر Pair
        pairButton = new JButton("Pair");
        pairButton.setBounds(50, 120, 100, 30);
        add(pairButton);

        // زر Leave
        leaveButton = new JButton("Leave");
        leaveButton.setBounds(160, 120, 100, 30);
        add(leaveButton);

        // إضافة الأحداث
        pairButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // عند الضغط على الزر، ابدأ الاتصال وأدخل الـ "Waiting Room"
                String name = nameField.getText();
                if (!name.isEmpty()) {
                    // أضف هنا كود الإرسال إلى السيرفر أو أي عملية تحتاجها
                    System.out.println("Pairing with name: " + name);
                    // الانتقال إلى فريم Waiting
                    wait waitingFrame = new wait(name);
                    waitingFrame.setVisible(true);
                    setVisible(false);
                } else {
                    JOptionPane.showMessageDialog(null, "Please enter your name.");
                }
            }
        });
         leaveButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // هنا يمكن إضافة كود للخروج أو ترك الجلسة
                System.out.println("Leaving...");
                // أغلق الفريم الحالي
                dispose();
            }
        });
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        test startFrame = new test();
        startFrame.setVisible(true);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

